### ISSUE TITLE
Is index.ts supposed to be empty?

### ISSUE THREAD

**Issue by roschler** [Rapyd-Samples/accept-payments#1]
The source file named `index.ts` is completely blank.  Is it supposed to be?

https://github.com/Rapyd-Samples/accept-payments/blob/main/nodejs/src/index.ts

**Comment by ismailbahadir** [comment]
hello, my name is ismail bahadir. I'm 39 years old. i am civil engineer. for 16 years. I took different tasks in many projects. I live in Turkey. in Ankara. I am married. I have 3 daughters. I work as an editor at Bahadir sheet metal profile metal engineering construction contracting trade limited company. I am effective in decision making in the company. iron, steel, npi, npu, h, u etc. Besides iron products, we sell 80%-90% of construction materials. We also do construction. We are decorating, we are drawing projects. We want to do business wherever in the world. We buy and sell real estate. the owner of our company is gulsum dogruoz. During the membership completion process, we became a member of many places. Names, e-mail addresses, passwords mixed up. but they all belong to our company, isobahadir83@gmail.com bahadirismail83@gmail.com Ms. gulsum and common e-mail addresses +905325971480 this number is the company phone. We would like to remove the restrictions to work with you and join your family by completing our activations. take it easy. Best regards.
